version: "3"

vars:
  BUILD_SITE_DIR: target/build
  BUILD_DIR: target
  CONTENT_DIR: content
  GOLANGCI_LINT_VERSION: v2.8.0

tasks:
  setup:
    desc: Install all required tools
    cmds:
      - task: setup:golangci-lint
      - echo "Setup complete!"

  setup:golangci-lint:
    desc: Install golangci-lint
    cmds:
      - |
        if command -v golangci-lint &> /dev/null; then
          echo "golangci-lint already installed: $(golangci-lint --version)"
        else
          echo "Installing golangci-lint {{.GOLANGCI_LINT_VERSION}}..."
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin {{.GOLANGCI_LINT_VERSION}}
          echo "golangci-lint installed successfully"
        fi

  default:
    desc: Run all validation tasks
    cmds:
      - task: validate

  validate:
    desc: Run all validation (fmt, lint, test, build)
    cmds:
      - task: fmt:check
      - task: lint
      - task: test
      - task: build

  fmt:
    desc: Format all Go files
    cmds:
      - go fmt ./...

  fmt:check:
    desc: Check if Go files are formatted
    cmds:
      - test -z "$(gofmt -l .)" || (echo "Files not formatted:" && gofmt -l . && exit 1)

  lint:
    desc: Run golangci-lint (skipped if not installed)
    cmds:
      - |
        if command -v golangci-lint &> /dev/null; then
          golangci-lint run ./...
        else
          echo "golangci-lint not installed, skipping lint (run 'task setup' to install)"
        fi

  test:
    desc: Run all tests
    cmds:
      - go test ./...

  test:coverage:
    desc: Run tests with coverage report
    cmds:
      - go test ./... -coverprofile={{.BUILD_DIR}}/coverage.out
      - go tool cover -func={{.BUILD_DIR}}/coverage.out

  test:coverage:html:
    desc: Generate HTML coverage report
    cmds:
      - go test ./... -coverprofile={{.BUILD_DIR}}/coverage.out
      - go tool cover -html={{.BUILD_DIR}}/coverage.out -o {{.BUILD_DIR}}/coverage.html
      - echo "Coverage report generated at {{.BUILD_DIR}}/coverage.html"

  test:unit:
    desc: Run only unit tests (internal packages)
    cmds:
      - go test ./internal/...

  test:integration:
    desc: Run only integration tests
    cmds:
      - go test -run "TestSiteGeneration|TestLinksAreValid|TestMarkdownFiles" .

  build:
    desc: Build the binary
    cmds:
      - go build -o {{.BUILD_DIR}}/

  generate:
    desc: Generate the static site
    cmds:
      - rm -rf {{.BUILD_SITE_DIR}}
      - go run .

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf {{.BUILD_DIR}}

  dev:
    desc: Run generate and serve locally
    deps: [generate]
    cmds:
      - echo "Serving at http://localhost:8080"
      - cd {{.BUILD_SITE_DIR}} && python3 -m http.server 8080

  dev:watch:
    desc: Serve locally with live reload (requires browser-sync and fswatch)
    cmds:
      - |
        if ! command -v browser-sync &> /dev/null; then
          echo "browser-sync not installed. Install with: npm install -g browser-sync"
          exit 1
        fi
        if ! command -v fswatch &> /dev/null; then
          echo "fswatch not installed. Install with: brew install fswatch"
          exit 1
        fi
        task generate
        echo "Starting browser-sync with live reload..."
        browser-sync start --server {{.BUILD_SITE_DIR}} --watch &
        BROWSER_SYNC_PID=$!
        trap "kill $BROWSER_SYNC_PID 2>/dev/null" EXIT
        sleep 2
        echo "Watching for changes in {{.CONTENT_DIR}}, internal, models..."
        while true; do
          fswatch -1 {{.CONTENT_DIR}} internal models && task generate && browser-sync reload
        done

  deps:verify:
    desc: Verify Go dependencies
    cmds:
      - go mod verify
